siteTitle = "5 minutes of React podcast"
siteDescr = "Podcast about React hot topics and JavaScript ecosystem."

siteTwitterUrl = "https://twitter.com/5minreact_audio"
siteEmailUrl = "mailto:podcast@5minreact.audio"
siteRssUrl = "http://feeds.soundcloud.com/users/soundcloud:users:304879382/sounds.rss"
siteAndroidUrl = "http://www.subscribeonandroid.com./feeds.soundcloud.com/users/soundcloud:users:304879382/sounds.rss"
siteItunesUrl = "https://itunes.apple.com/ru/podcast/5-minutes-of-react/id1232187990?mt=2&at=1010lwCk
&l=en"
siteSoundcloudUrl = "https://soundcloud.com/5minreact_audio"
siteYouTubeUrl = "https://www.youtube.com/channel/UC43OeCrRbp6hSEnNZWIHOGg/videos?flow=list&live_view=500&view=0&sort=dd"

googleAnalyticsId = "UA-96344565-2"

linkPrefix = "/"